apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
    release: my-prometheus-operator
spec:
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.endpoint }}
      interval: 10s