apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  labels:
    app: mysql
    tier: backend
spec:
  selector:
    app: keycloak-mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - name: keycloak-mysql
          image: mysql:5.7.25
          env:
            - name: MYSQL_DATABASE
              value: keycloak
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: keycloak
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: keycloak-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: keycloak-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: keycloak-mysql-pv-claim