apiVersion: v1
kind: Service
metadata:
  name: bookservice-service
  labels:
    app: bookservice
    tier: frontend
spec:
  selector:
    app: bookservice
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookservice
  template:
    metadata:
      labels:
        app: bookservice
    spec:
      containers:
        - name: bookservice
          image: docker.mycompany.com/book-service:1.0.0
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MONGODB_HOST
              value: my-mongodb
            - name: KEYCLOAK_HOST
              value: my-keycloak-http
            - name: KEYCLOAK_PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
