apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration-job
  labels:
    app: postgres
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
        - name: kong-migration
          image: kong:1.1.1
          env:
            - name: KONG_NGINX_DAEMON
              value: 'off'
            - name: KONG_PG_DATABASE
              value: kong
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PG_HOST
              value: my-postgres-postgresql
          command: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
      restartPolicy: Never