kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
         app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.3
        ports:
        - containerPort: 27017