{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "author-book-api.serviceAccountName" . }}
  labels:
{{ include "author-book-api.labels" . | nindent 4 }}
{{- end -}}
